version: '3'
services:
  api-service:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app

  frontend-service:
    build: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api-service
    environment:
      - API_URL=http://api-service:5000

    command: >
      streamlit run main.py 
      --server.address=0.0.0.0 
      --theme.primaryColor="#0083B8"
      --theme.backgroundColor="#FFFFFF"
      --theme.secondaryBackgroundColor="#F0F2F6"
      --theme.textColor="#262730"
      --theme.font="sans serif"