[theme]
primaryColor = "#1ABC9C"        # Verde Turquesa (Health Tech)
backgroundColor = "#F8F9FA"     # Fundo Cinza Suave (Off-White)
secondaryBackgroundColor = "#FFFFFF" # Barra lateral Branca (Clean)
textColor = "#2C3E50"           # Cinza Chumbo (Alto contraste)
font = "sans serif"

[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false